### ISSUE TITLE
DemoLowtran.py fails in Python 2.7

### ISSUE THREAD

**Issue by brian-rose** [scienceopen/lowtran#2]
Great package! 
The demo script fails on Python 2.7 because the `exist_ok` parameter for `os.makedirs()` is not supported. The demo runs smoothly when I replace
```
    makedirs('out',exist_ok=True)
```
with
```
    makedirs('out')
```

**Comment by scienceopen** [comment]
Hi @brian-rose thanks for your note.
In Python2, if the directory already exists you'll get ``OSError: [Errno 17] File exists: '.local'`` and in Python3 the same ``FileExistsError``.

In this case the ``makedirs`` was not really needed so I removed it. Everything does run then in Python 2.7 and 3.6
